CREATE DATABASE db_projeto_elite_wheelz;

use db_projeto_elite_wheelz;

CREATE TABLE TB_CLIENTE (
    ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NM_CLIENTE VARCHAR(200) NOT NULL,
    DS_CPF VARCHAR(150) NOT NULL UNIQUE,
    DS_TELEFONE VARCHAR(150) NOT NULL,
    DS_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    DS_CNH VARCHAR(500) NOT NULL UNIQUE
);

CREATE TABLE TB_TIPO_VEICULO (
    ID_TIPO_VEICULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DS_TIPO VARCHAR(100) NOT NULL
);

CREATE TABLE TB_VEICULO (
    ID_VEICULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_TIPO_VEICULO INT NOT NULL,
    DS_MODELO VARCHAR(150) NOT NULL,
    DS_MARCA VARCHAR(150) NOT NULL,
    DS_PLACA VARCHAR(150) NOT NULL UNIQUE,
    NR_ANO INT NOT NULL,
    FOREIGN KEY (ID_TIPO_VEICULO) REFERENCES TB_TIPO_VEICULO (ID_TIPO_VEICULO)
);

CREATE TABLE TB_LOCACAO (
    ID_LOCACAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    ID_VEICULO INT NOT NULL,
    NR_KM_RETIRADA VARCHAR(50) NOT NULL,
    DT_LOCACAO DATETIME NOT NULL,
    BT_SEGURO BOOLEAN NOT NULL,
    DS_OBSERVACOES VARCHAR(800) NOT NULL,
    DS_SITUACAO VARCHAR(50) NOT NULL,
    NR_KM_ENTREGA INT NOT NULL,
    DT_ENTREGA DATETIME NOT NULL,
    VL_TOTAL DECIMAL(15, 2) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE),
    FOREIGN KEY (ID_VEICULO) REFERENCES TB_VEICULO (ID_VEICULO)
);

-- VIEWS

CREATE VIEW view_veiculo AS
    SELECT v.ID_VEICULO, tv.DS_TIPO, v.DS_MODELO, v.DS_MARCA, v.DS_PLACA, v.NR_ANO 
    FROM tb_veiculo v
        INNER JOIN tb_tipo_veiculo tv USING(ID_TIPO_VEICULO)
    ORDER BY `ID_VEICULO`;


CREATE VIEW view_locacao AS
    SELECT l.ID_LOCACAO, ID_CLIENTE, cl.NM_CLIENTE, cl.DS_CPF, l.ID_VEICULO, v.DS_MODELO, v.DS_PLACA, v.NR_ANO, 
           l.NR_KM_RETIRADA, l.DT_LOCACAO, l.BT_SEGURO, l.DS_OBSERVACOES, l.DS_SITUACAO, l.NR_KM_ENTREGA, l.DT_ENTREGA,
           l.VL_TOTAL
    FROM TB_LOCACAO l
        INNER JOIN tb_cliente cl USING(ID_CLIENTE)
        INNER JOIN tb_veiculo v USING(ID_VEICULO)
    ORDER BY `ID_LOCACAO`;