CREATE TABLE TB_CLIENTE (
    ID_CLIENTE     INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NM_CLIENTE     VARCHAR(200) NOT NULL,
    DS_CPF         VARCHAR(150) NOT NULL,
    DS_TELEFONE    VARCHAR(150) NOT NULL,
    DS_EMAIL       VARCHAR(100) NOT NULL,
    DS_CNH         VARCHAR(500) NOT NULL
);

CREATE TABLE TB_TIPO_VEICULO (
    ID_TIPO_VEICULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DS_TIPO         VARCHAR(100) NOT NULL
);

CREATE TABLE TB_VEICULO (
    ID_VEICULO      INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_TIPO_VEICULO INT NOT NULL,
    DS_MODELO       VARCHAR(150) NOT NULL,
    DS_MARCA        VARCHAR(150) NOT NULL,
    DS_PLACA        VARCHAR(150) NOT NULL,
    NR_ANO          INT NOT NULL,
    FOREIGN KEY (ID_TIPO_VEICULO) REFERENCES TB_TIPO_VEICULO(ID_TIPO_VEICULO)
);

CREATE TABLE TB_LOCACAO (
    ID_LOCACAO      INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE      INT NOT NULL,
    ID_VEICULO      INT NOT NULL,
    NR_KM_RETIRADA  VARCHAR(50) NOT NULL,
    DT_LOCACAO      DATETIME NOT NULL,
    BT_SEGURO       BOOLEAN NOT NULL,
    DS_OBSERVACOES  VARCHAR(800) NOT NULL,
    DS_SITUACAO     VARCHAR(50) NOT NULL,
    NR_KM_ENTREGA   INT NOT NULL,
    DT_ENTREGA      DATETIME NOT NULL,
    VL_TOTAL        DECIMAL(15,2) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_VEICULO) REFERENCES TB_VEICULO(ID_VEICULO)
);

